import string
from mutagen.easyid3 import EasyID3
import os

Surahnames = [
     'Al-Fatiha'
    ,'Al-Baqarah'
    ,'Al-Imran'
    ,'An-Nisa'
    ,'Al-Maidah'
    ,'Al-Anam'
    ,'Al-Araf'
    ,'Al-Anfal'
    ,'Al-Tawbah'
    ,'Yunus'
    ,'Hud'
    ,'Yusuf'
    ,'Ar-Rad'
    ,'Ibrahim'
    ,'Al-Hijr'
    ,'An-Nahl'
    ,'Al-Isra'
    ,'Al-Kahf'
    ,'Maryam'
    ,'Ta-Ha'
    ,'Al-Anbiya'
    ,'Al-Hajj'
    ,'Al-Muminun'
    ,'An-Nur'
    ,'Al-Furqan'
    ,'Ash-Shuara'
    ,'An-Naml'
    ,'Al-Qasas'
    ,'Al-Ankabut'
    ,'Ar-Rum'
    ,'Luqman'
    ,'As-Sajda'
    ,'Al-Ahzab'
    ,'Saba'
    ,'Fatir'
    ,'Ya-Sin'
    ,'As-Saffat'
    ,'Sad'
    ,'Az-Zumar'
    ,'Ghafir'
    ,'Fussilat'
    ,'Ash-Shura'
    ,'Az-Zukhruf'
    ,'Ad-Dukhan'
    ,'Al-Jathiyah'
    ,'Al-Ahqaf'
    ,'Muhammad'
    ,'Al-Fath'
    ,'Al-Hujurat'
    ,'Qaf'
    ,'Adh-Dhariyat'
    ,'At-Tur'
    ,'An-Najm'
    ,'Al-Qamar'
    ,'Ar-Rahman'
    ,'Al-Waqia'
    ,'Al-Hadid'
    ,'Al-Mujadila'
    ,'Al-Hashr'
    ,'Al-Mumtahina'
    ,'As-Saff'
    ,'Al-Jumuah'
    ,'Al-Munafiqun'
    ,'At-Taghabun'
    ,'At-Talaq'
    ,'At-Tahrim'
    ,'Al-Mulk'
    ,'Al-Qalam'
    ,'Al-Haaqqa'
    ,'Al-Maarij'
    ,'Nuh'
    ,'Al-Jinn'
    ,'Al-Muzzammil'
    ,'Al-Muddathir'
    ,'Al-Qiyama'
    ,'Al-Insan'
    ,'Al-Mursalat'
    ,'An-Naba'
    ,'An-Naziaat'
    ,'Abasa'
    ,'At-Takwir'
    ,'Al-Infitar'
    ,'Al-Mutaffifin'
    ,'Al-Inshiqaq'
    ,'Al-Buruj'
    ,'At-Tariq'
    ,'Al-Ala'
    ,'Al-Ghashiyah'
    ,'Al-Fajr'
    ,'Al-Balad'
    ,'Ash-Shams'
    ,'Al-Lail'
    ,'Ad-Duha'
    ,'Ash-Sharh'
    ,'At-Tin'
    ,'Al-Alaq'
    ,'Al-Qadr'
    ,'Al-Bayyina'
    ,'Az-Zalzalah'
    ,'Al-Adiyat'
    ,'Al-Qaria'
    ,'At-Takathur'
    ,'Al-Asr'
    ,'Al-Humazah'
    ,'Al-Fil'
    ,'Quraish'
    ,'Al-Maaun'
    ,'Al-Kawthar'
    ,'Al-Kafirun'
    ,'An-Nasr'
    ,'Al-Masad'
    ,'Al-Ikhlas'
    ,'Al-Falaq'
    ,'An-Nas'
  ]

def get_files_in_directory(directory):
    files = []
    for root, _, filenames in os.walk(directory):
        for filename in filenames:
            append_to_file(f'<Surah Idx="1" ContentRefrence="{filename}" Duration="25:30"/>')
            print(filename)
            
    return files

def append_to_file( data):
    try:
        with open("Surahnames.xml", 'a' ,encoding='utf-8') as file:
            file.write(data)
            file.write('\n')  # Optionally, add a newline after each entry
    except Exception as e:
        print("Error:", e)

directory_path = './'
all_files = get_files_in_directory(directory_path)
print("All files in directory:", all_files)